name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - ruby-head
          - '3.3'
          - '3.2'
          - '3.1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      continue-on-error: ${{ (matrix.ruby_version == 'ruby-head')}}
    - name: Run the default task
      run: bundle exec rake
      continue-on-error: ${{ (matrix.ruby_version == 'ruby-head')}}
